### ISSUE TITLE
No Results in Output tab

### ISSUE THREAD

**Issue by mikeburns7** [danishsarwar99/reverse-search#3]
I am searching for a string in a folder of files that I know doesnt exist in any of the files but I am not getting any results in the output tab

**Comment by danishsarwar99** [comment]
Hi, I read your review in the marketplace and double-checked the extension and it is working fine for me. I am unable to replicate the issue.

**Comment by mikeburns7** [comment]
I have attached a GIF. Showing my test
![2020-03-25_13h39_32](https://user-images.githubusercontent.com/57635375/77567915-37e71280-6e9e-11ea-832b-d3ba6b61cf65.gif)

**Comment by mikeburns7** [comment]
Was that screen share helpful. Am I doing something wrong to have it not work?

**Comment by trillian74** [comment]
I experience the same result as @mikeburns7

**Comment by danishsarwar99** [comment]
Reverse Search is not including txt files for now.

**Comment by RichardsonWTR** [comment]
I'm having the same problem with a rails project. 
@danishsarwar99 , it's supposed to work with .rb files?
It's just normal text files with a different extension.

The search result in '0 files found', and sometimes don't even show me a response, showing only a 'processing' notification. 
I'm not filtering for files, I've just searched for some thrash text, like 'akfjasdkjsdkjfsdlkf'.

I'm using Reverse search 2.0.2
VS Code 1.56.2

**Comment by RichardsonWTR** [comment]
I appreciate the work on this extension, but it's just not working for me. 
For someone else who needs help, you can try this simple linux command 

```bash
# list all the *.txt files in the ~/repos folder not containing the text "Green"
egrep -irL --include=*.txt "Green" ~/repos/ 
```

**Comment by danishsarwar99** [comment]
HI, @RichardsonWTR  Thank you for the feedback. Yes, it is supposed to work with any kind of file as long as they are opened in VS Code.
Some of my colleagues are facing the same problem with the new version. I'll look into it and fix it ASAP.
