### ISSUE TITLE
Include reverse-search in "Problems" search bar 

### ISSUE THREAD

**Issue by manesioz** [danishsarwar99/reverse-search#6]
### Context 
If I am linting a project and it has a ton of repeated (but minor) issues and I want to quickly scan all other issues, I am not able to easily filter the search results to only contain results that do not contain some text string. 

### Proposal 
It would be awesome if you would be able to support reverse search filtering on the search bar of the "problems" tab, beside the output/terminal/debug console tabs. 

Thanks!

**Comment by danishsarwar99** [comment]
Nice proposal. I'll sure take a look into it in next version.
