### ISSUE TITLE
Publish new version in the vscode-marketplace

### ISSUE THREAD

**Issue by ironicnet** [danishsarwar99/reverse-search#7]
The feature merged in #2 is great, and it would make this plugin even more useful.

Can we publish a version to the vscode-marketplace ?

the feature doesn't seem to be present

**Comment by ctf0** [comment]
the feature is published but doesnt work because both are async & the ext wasnt waiting for them to fully init, its fixed in https://github.com/danishsarwar99/reverse-search/pull/10

**Comment by danishsarwar99** [comment]
Fixed and published with #10
