### ISSUE TITLE
Restrict reverse search to files with the name X

### ISSUE THREAD

**Issue by jacques-hoventer** [danishsarwar99/reverse-search#9]
It would be nice to be able to search e.g. all TSConfig.json files that do NOT have the string "XYZ". 

From your code it looks like you are creating pickers to do just that, but when I press enter it automatically jumps to searching files never asking me to filter by file names (include, exclude). 

		const termPick = createPicker('Enter a String');
		const includePick = createPicker("Files to Include (Optional)");
		const excludePick = createPicker("Files to Exclude (Optional)");

**Comment by ctf0** [comment]
check https://github.com/danishsarwar99/reverse-search/pull/10

**Comment by danishsarwar99** [comment]
#10 Merged. You won't see this issue now.
